version: '3.8' # Docker Compose 버전 지정

services:
  issuemoa-config: # 웹 애플리케이션 서비스 정의
    image: issuemoa/config:latest # 사용할 Docker 이미지 지정
    ports:
      - "8888:8888" # 호스트 포트와 컨테이너 포트 매핑
    environment:
      - "SPRING_PROFILES_ACTIVE=dev" # 도커 이미지에 환경 변수를 전달
    networks:
      issuemoa: # 서비스가 속한 네트워크 이름을 지정
        aliases:
          - "issuemoa-config" # 네트워크상의 서비스에 대한 대체 호스트 이름을 지정
  issuemoa-eureka:
    image: issuemoa/eureka:latest
    ports:
      - "8761:8761"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      issuemoa:
        aliases:
          - "issuemoa-eureka"
  issuemoa-voca:
    image: issuemoa/voca:latest
    ports:
      - "17080:17080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      issuemoa:
        aliases:
          - "issuemoa-voca"
    depends_on:
      - issuemoa-config
networks:
  issuemoa: # 사용할 네트워크 정의
    driver: bridge
